import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import { UserProvider } from "@/context/AdminContext";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Northeast Voyage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body
        // className={cn({
        //   "debug-screens": process.env.NODE_ENV === "development",
        // })}
        >
          <main className="font-primary">
            {children}
            <Toaster />
          </main>
        </body>
      </UserProvider>
    </html>
  );
}
